name: Wails build

on:
  release:
    types: [ created ]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build:
          - name: 'demo-app'
            platform: 'windows/amd64'
            os: 'windows-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          app-working-directory: app
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.23'
          package: false
          nsis: false

      - name: Compress
        run: |
          copy readme.md app\build\bin\
          copy LICENSE app\build\bin\
          Rename-Item -Path app\build\bin\${{ matrix.build.name }} -NewName ${{ matrix.build.name }}.exe
          Compress-Archive -Path app\build\bin\* -DestinationPath ${{ matrix.build.name }}.zip -CompressionLevel Optimal

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.build.name }}.zip
          asset_name: ${{ matrix.build.name }}-${{ github.event.release.tag_name }}-windows-amd64.zip
          asset_content_type: application/octet-stream


  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        build:
          - name: 'demo-app'
            platform: 'darwin/universal'
            os: 'macos-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          app-working-directory: app
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.23'
          package: false

      - name: List Files in Directory
        run: |
          ls -la app/build/bin

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/bin/${{ matrix.build.name }}.pkg
          asset_name: ${{ matrix.build.name }}-${{ github.event.release.tag_name }}-macos.pkg
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/bin/${{ matrix.build.name }}.app.zip
          asset_name: ${{ matrix.build.name }}-${{ github.event.release.tag_name }}-macos.app.zip
          asset_content_type: application/octet-stream


  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - name: 'demo-app'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          app-working-directory: app
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.23'
          package: false

      - name: move files
        run: |
          mkdir _temp_dist
          cp readme.md _temp_dist/
          cp LICENSE _temp_dist/
          cp -r app/build/bin/* _temp_dist/
          ls -la _temp_dist/
          cd _temp_dist/
          tar -czf ${{ matrix.build.name }}.tar.gz .

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.build.name }}.tar.gz
          asset_name: ${{ matrix.build.name }}-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          asset_content_type: application/octet-stream
